name: Build
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io/treebeardtech/dev-images
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: npm install -g @devcontainers/cli@v0.30.0
      - run: |
            set -e -x -u -o pipefail
            repo=ghcr.io/treebeardtech/dev-images; tag=latest
            docker pull hello-world
            docker tag hello-world $repo:$tag
            # devcontainer build \
            #     --workspace-folder . \
            #     --config .devcontainer/vm/devcontainer.json \
            #     --image-name $repo:$tag
            docker push $repo:$tag